[2021-06-06 17:23:01,568] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: forex_data_pipeline.spark 2021-06-05T00:00:00+00:00 [None]>
[2021-06-06 17:23:01,676] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: forex_data_pipeline.spark 2021-06-05T00:00:00+00:00 [None]>
[2021-06-06 17:23:01,678] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-06-06 17:23:01,681] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-06-06 17:23:01,685] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-06-06 17:23:01,898] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): spark> on 2021-06-05T00:00:00+00:00
[2021-06-06 17:23:01,909] {standard_task_runner.py:52} INFO - Started process 1578 to run task
[2021-06-06 17:23:01,918] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'forex_data_pipeline', 'spark', '2021-06-05T00:00:00+00:00', '--job-id', '49', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_spark.py', '--cfg-path', '/tmp/tmpwr5zuy0t', '--error-file', '/tmp/tmpblom1o5k']
[2021-06-06 17:23:01,938] {standard_task_runner.py:77} INFO - Job 49: Subtask spark
[2021-06-06 17:23:02,158] {logging_mixin.py:104} INFO - Running <TaskInstance: forex_data_pipeline.spark 2021-06-05T00:00:00+00:00 [running]> on host 72eec67484fb
[2021-06-06 17:23:02,469] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=admin@localhost.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=forex_data_pipeline
AIRFLOW_CTX_TASK_ID=spark
AIRFLOW_CTX_EXECUTION_DATE=2021-06-05T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-06-05T00:00:00+00:00
[2021-06-06 17:23:54,585] {logging_mixin.py:104} WARNING - Traceback (most recent call last):
[2021-06-06 17:23:54,605] {logging_mixin.py:104} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/serializers.py", line 437, in dumps
    return cloudpickle.dumps(obj, pickle_protocol)
[2021-06-06 17:23:54,610] {logging_mixin.py:104} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/cloudpickle/cloudpickle_fast.py", line 101, in dumps
    cp.dump(obj)
[2021-06-06 17:23:54,617] {logging_mixin.py:104} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/cloudpickle/cloudpickle_fast.py", line 540, in dump
    return Pickler.dump(self, obj)
[2021-06-06 17:23:54,638] {logging_mixin.py:104} WARNING -   File "/usr/local/lib/python3.7/pickle.py", line 437, in dump
    self.save(obj)
[2021-06-06 17:23:54,647] {logging_mixin.py:104} WARNING -   File "/usr/local/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
[2021-06-06 17:23:54,655] {logging_mixin.py:104} WARNING -   File "/usr/local/lib/python3.7/pickle.py", line 789, in save_tuple
    save(element)
[2021-06-06 17:23:54,664] {logging_mixin.py:104} WARNING -   File "/usr/local/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
[2021-06-06 17:23:54,670] {logging_mixin.py:104} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/cloudpickle/cloudpickle_fast.py", line 722, in save_function
    *self._dynamic_function_reduce(obj), obj=obj
[2021-06-06 17:23:54,703] {logging_mixin.py:104} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/cloudpickle/cloudpickle_fast.py", line 659, in _save_reduce_pickle5
    dictitems=dictitems, obj=obj
[2021-06-06 17:23:54,713] {logging_mixin.py:104} WARNING -   File "/usr/local/lib/python3.7/pickle.py", line 638, in save_reduce
    save(args)
[2021-06-06 17:23:54,728] {logging_mixin.py:104} WARNING -   File "/usr/local/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
[2021-06-06 17:23:54,730] {logging_mixin.py:104} WARNING -   File "/usr/local/lib/python3.7/pickle.py", line 789, in save_tuple
    save(element)
[2021-06-06 17:23:54,788] {logging_mixin.py:104} WARNING -   File "/usr/local/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
[2021-06-06 17:23:54,801] {logging_mixin.py:104} WARNING -   File "/usr/local/lib/python3.7/pickle.py", line 774, in save_tuple
    save(element)
[2021-06-06 17:23:54,880] {logging_mixin.py:104} WARNING -   File "/usr/local/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
[2021-06-06 17:23:54,888] {logging_mixin.py:104} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/dill/_dill.py", line 1177, in save_cell
    f = obj.cell_contents
[2021-06-06 17:23:54,894] {logging_mixin.py:104} WARNING - ValueError: Cell is empty
[2021-06-06 17:23:54,903] {taskinstance.py:1455} ERROR - Could not serialize object: ValueError: Cell is empty
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/serializers.py", line 437, in dumps
    return cloudpickle.dumps(obj, pickle_protocol)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/cloudpickle/cloudpickle_fast.py", line 101, in dumps
    cp.dump(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/cloudpickle/cloudpickle_fast.py", line 540, in dump
    return Pickler.dump(self, obj)
  File "/usr/local/lib/python3.7/pickle.py", line 437, in dump
    self.save(obj)
  File "/usr/local/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.7/pickle.py", line 789, in save_tuple
    save(element)
  File "/usr/local/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/cloudpickle/cloudpickle_fast.py", line 722, in save_function
    *self._dynamic_function_reduce(obj), obj=obj
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/cloudpickle/cloudpickle_fast.py", line 659, in _save_reduce_pickle5
    dictitems=dictitems, obj=obj
  File "/usr/local/lib/python3.7/pickle.py", line 638, in save_reduce
    save(args)
  File "/usr/local/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.7/pickle.py", line 789, in save_tuple
    save(element)
  File "/usr/local/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.7/pickle.py", line 774, in save_tuple
    save(element)
  File "/usr/local/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/airflow/.local/lib/python3.7/site-packages/dill/_dill.py", line 1177, in save_cell
    f = obj.cell_contents
ValueError: Cell is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 33, in execute_spark
    dfFromData2 = spark.createDataFrame(data).toDF(*columns)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/session.py", line 675, in createDataFrame
    return self._create_dataframe(data, schema, samplingRatio, verifySchema)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/session.py", line 701, in _create_dataframe
    jrdd = self._jvm.SerDeUtil.toJavaArray(rdd._to_java_object_rdd())
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/rdd.py", line 2618, in _to_java_object_rdd
    return self.ctx._jvm.SerDeUtil.pythonToJava(rdd._jrdd, True)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/rdd.py", line 2950, in _jrdd
    self._jrdd_deserializer, profiler)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/rdd.py", line 2828, in _wrap_function
    pickled_command, broadcast_vars, env, includes = _prepare_for_python_RDD(sc, command)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/rdd.py", line 2814, in _prepare_for_python_RDD
    pickled_command = ser.dumps(command)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/serializers.py", line 447, in dumps
    raise pickle.PicklingError(msg)
_pickle.PicklingError: Could not serialize object: ValueError: Cell is empty
[2021-06-06 17:23:55,153] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=forex_data_pipeline, task_id=spark, execution_date=20210605T000000, start_date=20210606T172301, end_date=20210606T172355
[2021-06-06 17:23:55,805] {local_task_job.py:146} INFO - Task exited with return code 1
