[2021-06-06 16:03:54,984] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: forex_data_pipeline.spark_submit_job 2021-06-05T00:00:00+00:00 [queued]>
[2021-06-06 16:03:55,055] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: forex_data_pipeline.spark_submit_job 2021-06-05T00:00:00+00:00 [queued]>
[2021-06-06 16:03:55,058] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-06-06 16:03:55,060] {taskinstance.py:1043} INFO - Starting attempt 7 of 8
[2021-06-06 16:03:55,062] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-06-06 16:03:55,112] {taskinstance.py:1063} INFO - Executing <Task(SparkSubmitOperator): spark_submit_job> on 2021-06-05T00:00:00+00:00
[2021-06-06 16:03:55,134] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'forex_data_pipeline', 'spark_submit_job', '2021-06-05T00:00:00+00:00', '--job-id', '39', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_spark.py', '--cfg-path', '/tmp/tmphmlixwbz', '--error-file', '/tmp/tmpfxae7x5z']
[2021-06-06 16:03:55,147] {standard_task_runner.py:77} INFO - Job 39: Subtask spark_submit_job
[2021-06-06 16:03:55,125] {standard_task_runner.py:52} INFO - Started process 2805 to run task
[2021-06-06 16:03:55,317] {logging_mixin.py:104} INFO - Running <TaskInstance: forex_data_pipeline.spark_submit_job 2021-06-05T00:00:00+00:00 [running]> on host 5b1a5e9e3fee
[2021-06-06 16:03:55,533] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=admin@localhost.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=forex_data_pipeline
AIRFLOW_CTX_TASK_ID=spark_submit_job
AIRFLOW_CTX_EXECUTION_DATE=2021-06-05T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-06-05T00:00:00+00:00
[2021-06-06 16:03:55,608] {base.py:74} INFO - Using connection to: id: spark_conn. Host: spark://spark-master, Port: 7077, Schema: , Login: marcelo, Password: XXXXXXXX, extra: None
[2021-06-06 16:03:55,616] {spark_submit.py:364} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --conf master=spark://spark-master:7077 --num-executors 1 --total-executor-cores 1 --executor-cores 1 --executor-memory 512m --driver-memory 512m --name airflow-spark1 /opt/airflow/dags/test.py
[2021-06-06 16:04:03,837] {spark_submit.py:526} INFO - Warning: Ignoring non-Spark config property: master
[2021-06-06 16:04:04,901] {spark_submit.py:526} INFO - WARNING: An illegal reflective access operation has occurred
[2021-06-06 16:04:04,913] {spark_submit.py:526} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/airflow/.local/lib/python3.7/site-packages/pyspark/jars/spark-unsafe_2.12-3.1.2.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2021-06-06 16:04:04,929] {spark_submit.py:526} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2021-06-06 16:04:04,936] {spark_submit.py:526} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2021-06-06 16:04:04,950] {spark_submit.py:526} INFO - WARNING: All illegal access operations will be denied in a future release
[2021-06-06 16:04:08,433] {spark_submit.py:526} INFO - 21/06/06 16:04:08 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2021-06-06 16:04:16,078] {spark_submit.py:526} INFO - Traceback (most recent call last):
[2021-06-06 16:04:16,093] {spark_submit.py:526} INFO - File "/opt/airflow/dags/test.py", line 19, in <module>
[2021-06-06 16:04:16,098] {spark_submit.py:526} INFO - dfFromData2 = spark.createDataFrame(data).toDF(*columns)
[2021-06-06 16:04:16,108] {spark_submit.py:526} INFO - NameError: name 'spark' is not defined
[2021-06-06 16:04:16,287] {spark_submit.py:526} INFO - log4j:WARN No appenders could be found for logger (org.apache.spark.util.ShutdownHookManager).
[2021-06-06 16:04:16,293] {spark_submit.py:526} INFO - log4j:WARN Please initialize the log4j system properly.
[2021-06-06 16:04:16,297] {spark_submit.py:526} INFO - log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[2021-06-06 16:04:16,740] {taskinstance.py:1455} ERROR - Cannot execute: spark-submit --master spark://spark-master:7077 --conf master=spark://spark-master:7077 --num-executors 1 --total-executor-cores 1 --executor-cores 1 --executor-memory 512m --driver-memory 512m --name airflow-spark1 /opt/airflow/dags/test.py. Error code is: 1.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 183, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 455, in submit
    self._mask_cmd(spark_submit_cmd), returncode
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --conf master=spark://spark-master:7077 --num-executors 1 --total-executor-cores 1 --executor-cores 1 --executor-memory 512m --driver-memory 512m --name airflow-spark1 /opt/airflow/dags/test.py. Error code is: 1.
[2021-06-06 16:04:16,768] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=forex_data_pipeline, task_id=spark_submit_job, execution_date=20210605T000000, start_date=20210606T160354, end_date=20210606T160416
[2021-06-06 16:04:16,916] {local_task_job.py:146} INFO - Task exited with return code 1
