[2021-06-06 14:48:40,087] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: forex_data_pipeline.spark1 2021-06-05T00:00:00+00:00 [queued]>
[2021-06-06 14:48:40,126] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: forex_data_pipeline.spark1 2021-06-05T00:00:00+00:00 [queued]>
[2021-06-06 14:48:40,127] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-06-06 14:48:40,129] {taskinstance.py:1043} INFO - Starting attempt 13 of 14
[2021-06-06 14:48:40,131] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-06-06 14:48:40,147] {taskinstance.py:1063} INFO - Executing <Task(SparkSubmitOperator): spark1> on 2021-06-05T00:00:00+00:00
[2021-06-06 14:48:40,156] {standard_task_runner.py:52} INFO - Started process 164 to run task
[2021-06-06 14:48:40,166] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'forex_data_pipeline', 'spark1', '2021-06-05T00:00:00+00:00', '--job-id', '29', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_spark.py', '--cfg-path', '/tmp/tmpwqubysr2', '--error-file', '/tmp/tmpqstbbx2i']
[2021-06-06 14:48:40,168] {standard_task_runner.py:77} INFO - Job 29: Subtask spark1
[2021-06-06 14:48:40,278] {logging_mixin.py:104} INFO - Running <TaskInstance: forex_data_pipeline.spark1 2021-06-05T00:00:00+00:00 [running]> on host 5b1a5e9e3fee
[2021-06-06 14:48:40,371] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=admin@localhost.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=forex_data_pipeline
AIRFLOW_CTX_TASK_ID=spark1
AIRFLOW_CTX_EXECUTION_DATE=2021-06-05T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-06-05T00:00:00+00:00
[2021-06-06 14:48:40,395] {base.py:74} INFO - Using connection to: id: spark_conn. Host: spark://spark-master, Port: 7077, Schema: , Login: marcelo, Password: XXXXXXXX, extra: None
[2021-06-06 14:48:40,400] {spark_submit.py:364} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --name arrow-spark /opt/airflow/dags/test.py
[2021-06-06 14:48:46,996] {spark_submit.py:526} INFO - WARNING: An illegal reflective access operation has occurred
[2021-06-06 14:48:46,998] {spark_submit.py:526} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/airflow/.local/lib/python3.7/site-packages/pyspark/jars/spark-unsafe_2.12-3.1.2.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2021-06-06 14:48:47,000] {spark_submit.py:526} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2021-06-06 14:48:47,001] {spark_submit.py:526} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2021-06-06 14:48:47,004] {spark_submit.py:526} INFO - WARNING: All illegal access operations will be denied in a future release
[2021-06-06 14:48:48,404] {spark_submit.py:526} INFO - 21/06/06 14:48:48 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2021-06-06 14:48:50,802] {spark_submit.py:526} INFO - Traceback (most recent call last):
[2021-06-06 14:48:50,804] {spark_submit.py:526} INFO - File "/opt/airflow/dags/test.py", line 17, in <module>
[2021-06-06 14:48:50,806] {spark_submit.py:526} INFO - dfFromData2 = spark.createDataFrame(data).toDF(*columns)
[2021-06-06 14:48:50,807] {spark_submit.py:526} INFO - NameError: name 'spark' is not defined
[2021-06-06 14:48:50,887] {spark_submit.py:526} INFO - log4j:WARN No appenders could be found for logger (org.apache.spark.util.ShutdownHookManager).
[2021-06-06 14:48:50,890] {spark_submit.py:526} INFO - log4j:WARN Please initialize the log4j system properly.
[2021-06-06 14:48:50,892] {spark_submit.py:526} INFO - log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[2021-06-06 14:48:51,105] {taskinstance.py:1455} ERROR - Cannot execute: spark-submit --master spark://spark-master:7077 --name arrow-spark /opt/airflow/dags/test.py. Error code is: 1.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 183, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 455, in submit
    self._mask_cmd(spark_submit_cmd), returncode
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --name arrow-spark /opt/airflow/dags/test.py. Error code is: 1.
[2021-06-06 14:48:51,116] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=forex_data_pipeline, task_id=spark1, execution_date=20210605T000000, start_date=20210606T144840, end_date=20210606T144851
[2021-06-06 14:48:51,219] {local_task_job.py:146} INFO - Task exited with return code 1
